//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingDatasetsDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamingDatasetsDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;@DatasetName&quot;,
        ///  &quot;defaultMode&quot;: &quot;PushStreaming&quot;,
        ///  &quot;tables&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Expenses&quot;,
        ///      &quot;columns&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;Amount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;TotalAmount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Budget&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;MaxAmount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        }
        ///      ]
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string DemoHybridDataset {
            get {
                return ResourceManager.GetString("DemoHybridDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;@DatasetName&quot;,
        ///  &quot;defaultMode&quot;: &quot;Push&quot;,
        ///  &quot;tables&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Expenses&quot;,
        ///      &quot;columns&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;Expense&quot;,
        ///          &quot;dataType&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Category&quot;,
        ///          &quot;dataType&quot;: &quot;string&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Amount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;,
        ///          &quot;formatString&quot;: &quot;$#,##0.00&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Time&quot;,
        ///          &quot;dataType&quot;: &quot;Datetime&quot;,
        ///          &quot;formatSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemoPushDataset {
            get {
                return ResourceManager.GetString("DemoPushDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;@DatasetName&quot;,
        ///  &quot;defaultMode&quot;: &quot;PushStreaming&quot;,
        ///  &quot;tables&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;Expenses&quot;,
        ///      &quot;columns&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;Amount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;TotalAmount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;Budget&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;MaxAmount&quot;,
        ///          &quot;dataType&quot;: &quot;Double&quot;
        ///        }
        ///      ]
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string DemoStreamingDataset {
            get {
                return ResourceManager.GetString("DemoStreamingDataset", resourceCulture);
            }
        }
    }
}
